const menu = [
  {
    id: 1,
    title: "Poha",
    category: "breakfast",
    price: 150,
    img: "/Images/item-3.webp",
    desc: `Poha is a nutrient dense food. It is a better option than cereals because it contains a lot of carbohydrates, protein, fibre, vitamins, and iron. All of these nutrients not only help you lose weight, but they also have a number of health benefits. `,
  },
  {
    id: 2,
    title: "Thepla",
    category: "breakfast",
    price: 130,
    img: "/Images/item-2.jpg",
    desc: `Thepla burns the excess calories and helps you in staying energized. Good for skin, eyes, and hair –the nutrients and vitamins present in Thepla help to promote glowing and healthy skin. It is also good for the eyes, liver, and nerves.`,
  },
  {
    id: 3,
    title: "Khaman Dhokla",
    category: "breakfast",
    price: 99,
    img: "/Images/item-4.jpg",
    desc: `Dhokla is a savoury sponge dish that is native to the Indian state of Gujarat and parts of adjacent states, and is popular throughout the country. It is made with a fermented batter that is steamed to a cake-like consistency.`,
  },
  {
    id: 4,
    title: "Dosa",
    category: "lunch",
    price: 199,
    img: "/Images/item-6.jpg",
    desc: `A dosa, also called dosai, is a thin pancake in South Indian cuisine made from a fermented batter of ground black lentils and rice. Dosas are popular in South Asia as well as around the world. Dosas are served hot, often with chutney and sambar. `,
  },
  {
    id: 5,
    title: "Gol gappa",
    category: "lunch",
    price: 22.99,
    img: "/images/item-11.webp",
    desc: `Gol gappa (also known as pani puri) is a popular bite-size chaat consisting of a hollow, crispy-fried puffed ball that is filled with potato, chickpeas, onions, spices, and flavoured water, usually tamarind or mint, and popped into one's mouth whole.`,
  },
  {
    id: 6,
    title: "Punjabi dish",
    category: "lunch",
    price: 299,
    img: "/Images/item-5.jpg",
    desc: `Punjabi cuisine is known for its rich, buttery flavours along with the extensive vegetarian and meat dishes. One of its main features is its diverse range of dishes. Restaurant-style dishes use large amounts of ghee and butter. Some food items are eaten daily while some delicacies are cooked only on special occasions`,
  },
  {
    id: 7,
    title: "pav-bhaji",
    category: "dinner",
    price: 199,
    img: "/Images/item-8.jpg",
    desc: `Pav Bhaji is a fast food dish from Mumbai (Bombay), India, consisting of a vegetable curry (bhaji) cooked in tomato gravy and served with a soft bread roll (pav).`,
  },
  {
    id: 8,
    title: "Veg-pulao",
    category: "lunch",
    price: 199,
    img: "/Images/item-7.jpg",
    desc: ` a dish originating from the East, consisting of rice flavoured with spices and cooked in stock, to which meat, poultry, or fish may be added.`,
  },
  {
    id: 9,
    title: "Pasta",
    category: "dinner",
    price: 199,
    img: "/Images/item-12.jpg",
    desc: `Pasta is a type of food typically made from an unleavened dough of wheat flour mixed with water or eggs, and formed into sheets or other shapes, then cooked by boiling or baking.`,
  },
  {
    id: 10,
    title: "Gajar Ka Halwa",
    category: "dessert",
    price: 199,
    img: "/Images/item-9.jpg",
    desc: `Gajar Ka Halwa contains all the nutrients that are excellent sources of Vitamin A, C and K. In addition to that it also contains healthy fats and is also a rich source of fibre and antioxidants.`,
  },
  {
    id: 11,
    title: "Gulab jamun",
    category: "dessert",
    price: 199,
    img: "/Images/item-10.jpg",
    desc: `Gulab jamun is an Indian dessert of fried dough balls that are soaked in a sweet, sticky sugar syrup. As per tradition, the syrup has a delicate rose flavour: Gulab means 'rose water' and jamun refers to a berry of a similar size and colour.`,
  },
];
export default menu;
